version: '3.7'

services:
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      DEBUG: 1
      SERVER_NAME: "localhost:80"
      MERCURE_PUBLISHER_JWT_KEY: "!ChangeMe!"
      MERCURE_SUBSCRIBER_JWT_KEY: "!ChangeMe!"
      MERCURE_EXTRA_DIRECTIVES: |-
        cors_origins http://localhost:8000 https://localhost:8000
        publish_origins *
        subscriptions
        heartbeat 15s
        demo
        ui
    command: caddy run -config /etc/caddy/Caddyfile.dev
    ports:
      - "8001:80"
      - "4433:443"
    volumes:
      - mercure_data:/data
      - mercure_config:/config

volumes:
  mercure_data:
  mercure_config:
