version: '3.7'

services:
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    env_file: .env
    environment:
      DEBUG: 1
      SERVER_NAME: "${MERCURE_HOST}:80"
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SECRET}
      MERCURE_EXTRA_DIRECTIVES: |-
        cors_origins ${APP_URL}
        publish_origins *
        subscriptions
        heartbeat 15s
    command: caddy run
    ports:
      - "9876:80"
    volumes:
      - mercure_data:/data
      - mercure_config:/config

volumes:
  mercure_data:
  mercure_config:
